<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.5.0</Version>
    <Description>Search abstractions and provider clients for mux</Description>
    <PackageId>Mux.Search</PackageId>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

</Project>
