namespace Mux.Core.Telemetry
{
    using System;

    /// <summary>
    /// A single recorded LLM call: the unit of durable usage telemetry. One instance corresponds to one
    /// model round-trip (one agent-loop iteration, one chat request, or one compaction/subagent call).
    /// Run- and session-level figures are sums over these rows. Timing fields are null when the provider
    /// did not report them. Instances are cheap POCOs; validation happens at the storage layer.
    /// </summary>
    public sealed class UsageEvent
    {
        #region Private-Members

        private string _EndpointName = string.Empty;
        private string _AdapterType = string.Empty;
        private string _Model = string.Empty;

        #endregion

        #region Public-Members

        /// <summary>
        /// The call-completion timestamp as Unix epoch milliseconds (UTC). Defaults to 0; the recorder
        /// stamps it at enqueue time when left unset.
        /// </summary>
        public long TimestampUnixMs { get; set; }

        /// <summary>
        /// The run correlation identifier, or null when the call is not part of an agent run.
        /// </summary>
        public string? RunId { get; set; }

        /// <summary>
        /// The persisted session identifier, or null when the call is not associated with a session.
        /// </summary>
        public string? SessionId { get; set; }

        /// <summary>
        /// The job identifier within a run (for example "primary"), or null.
        /// </summary>
        public string? JobId { get; set; }

        /// <summary>
        /// The kind of work that produced the call. Defaults to <see cref="UsageCallKindEnum.Primary"/>.
        /// </summary>
        public UsageCallKindEnum CallKind { get; set; } = UsageCallKindEnum.Primary;

        /// <summary>
        /// The high-level command mode that produced the call (for example "interactive", "print",
        /// "serve"), or null.
        /// </summary>
        public string? Command { get; set; }

        /// <summary>
        /// The endpoint name the call was made against. Required; defaults to empty and falls back to
        /// "unknown" at the storage layer when blank.
        /// </summary>
        public string EndpointName
        {
            get => _EndpointName;
            set => _EndpointName = value ?? string.Empty;
        }

        /// <summary>
        /// The provider/adapter family (for example "anthropic", "openai", "ollama"). Defaults to empty.
        /// </summary>
        public string AdapterType
        {
            get => _AdapterType;
            set => _AdapterType = value ?? string.Empty;
        }

        /// <summary>
        /// The model identifier used for the call. Defaults to empty.
        /// </summary>
        public string Model
        {
            get => _Model;
            set => _Model = value ?? string.Empty;
        }

        /// <summary>
        /// The endpoint base-URL host only (never the full URL, path, or query, which can carry secrets),
        /// or null when unknown.
        /// </summary>
        public string? BaseHost { get; set; }

        /// <summary>
        /// A local project label (the working-directory basename), or null. Never exported off-machine.
        /// </summary>
        public string? Project { get; set; }

        /// <summary>
        /// The agent-loop iteration index within the run, or null when not applicable.
        /// </summary>
        public int? Iteration { get; set; }

        /// <summary>
        /// Prompt/input tokens consumed by the call.
        /// </summary>
        public int InputTokens { get; set; }

        /// <summary>
        /// Cached/cache-read prompt tokens (a subset of the prompt served from cache). Zero when the
        /// provider does not report cache usage.
        /// </summary>
        public int CachedTokens { get; set; }

        /// <summary>
        /// Completion/output tokens generated by the call.
        /// </summary>
        public int OutputTokens { get; set; }

        /// <summary>
        /// Reasoning/thinking tokens billed separately. Zero when unreported.
        /// </summary>
        public int ReasoningTokens { get; set; }

        /// <summary>
        /// Total tokens reported by the provider.
        /// </summary>
        public int TotalTokens { get; set; }

        /// <summary>
        /// Time-to-first-token in milliseconds, or null when unreported.
        /// </summary>
        public long? TimeToFirstTokenMs { get; set; }

        /// <summary>
        /// Streaming duration (first token to completion) in milliseconds, or null.
        /// </summary>
        public long? StreamingMs { get; set; }

        /// <summary>
        /// Total request duration in milliseconds, or null.
        /// </summary>
        public long? TotalMs { get; set; }

        /// <summary>
        /// Overall output tokens per second, or null when unavailable.
        /// </summary>
        public double? TokensPerSecond { get; set; }

        /// <summary>
        /// The provider finish reason, or null.
        /// </summary>
        public string? FinishReason { get; set; }

        /// <summary>
        /// Whether the call succeeded.
        /// </summary>
        public bool Success { get; set; } = true;

        /// <summary>
        /// The error code when the call failed (for example "llm_connection_error"), or null on success.
        /// </summary>
        public string? ErrorCode { get; set; }

        /// <summary>
        /// The number of transport retries the call incurred.
        /// </summary>
        public int RetryCount { get; set; }

        /// <summary>
        /// The pricing-table version in effect when the row was written (audit only; cost is recomputed
        /// from the current table at read time), or null.
        /// </summary>
        public string? PricingVersion { get; set; }

        #endregion

        #region Constructors-and-Factories

        /// <summary>
        /// Initializes a new instance of the <see cref="UsageEvent"/> class.
        /// </summary>
        public UsageEvent()
        {
        }

        #endregion

        #region Public-Methods

        /// <summary>
        /// Builds a usage event for one completed (or errored) model call from the endpoint plus the client's
        /// last-call metrics and usage — the mapping the agent loop and the server chat routes previously each
        /// hand-rolled. Callers set any additional context (run/session/job ids, project, iteration, error
        /// code) on the returned instance.
        /// </summary>
        /// <param name="endpoint">The endpoint the call was made against. Must not be null.</param>
        /// <param name="call">The client's last-call metrics, or null when none was recorded.</param>
        /// <param name="usage">The provider-reported token usage, or null when unavailable.</param>
        /// <param name="callKind">The kind of call.</param>
        /// <param name="command">The command/context that made the call, or null.</param>
        /// <param name="success">Whether the call succeeded.</param>
        /// <param name="fallbackTtftMs">A client-measured time-to-first-token to use when metrics carry none
        /// (negative means unknown). Optional.</param>
        /// <param name="fallbackTotalMs">A client-measured total duration to use when metrics carry none.
        /// Optional.</param>
        /// <returns>A populated usage event.</returns>
        /// <exception cref="ArgumentNullException">Thrown when <paramref name="endpoint"/> is null.</exception>
        public static UsageEvent FromCall(
            Mux.Core.Models.EndpointConfig endpoint,
            Mux.Core.Llm.LlmCallMetrics? call,
            Mux.Core.Llm.LlmUsage? usage,
            UsageCallKindEnum callKind,
            string? command,
            bool success,
            long? fallbackTtftMs = null,
            long? fallbackTotalMs = null)
        {
            if (endpoint is null) throw new ArgumentNullException(nameof(endpoint));

            bool haveFallbackTtft = fallbackTtftMs.HasValue && fallbackTtftMs.Value >= 0;

            return new UsageEvent
            {
                CallKind = callKind,
                Command = string.IsNullOrEmpty(command) ? null : command,
                EndpointName = endpoint.Name,
                AdapterType = endpoint.AdapterType.ToString(),
                Model = string.IsNullOrEmpty(call?.Model) ? endpoint.Model : call!.Model!,
                BaseHost = HostFromUrl(endpoint.BaseUrl),
                InputTokens = usage?.InputTokens ?? 0,
                CachedTokens = usage?.CachedTokens ?? 0,
                OutputTokens = usage?.OutputTokens ?? 0,
                ReasoningTokens = usage?.ReasoningTokens ?? 0,
                TotalTokens = usage?.TotalTokens ?? 0,
                TimeToFirstTokenMs = call?.TimeToFirstTokenMs ?? (haveFallbackTtft ? fallbackTtftMs : null),
                StreamingMs = call?.StreamingMs ?? (haveFallbackTtft && fallbackTotalMs.HasValue ? (long?)Math.Max(0, fallbackTotalMs.Value - fallbackTtftMs!.Value) : null),
                TotalMs = call?.TotalMs ?? fallbackTotalMs,
                TokensPerSecond = call?.TokensPerSecond,
                FinishReason = call?.FinishReason,
                Success = success
            };
        }

        /// <summary>
        /// Extracts the host from a base URL, or null when it is blank or not an absolute URL.
        /// </summary>
        /// <param name="baseUrl">The base URL.</param>
        /// <returns>The host, or null.</returns>
        public static string? HostFromUrl(string? baseUrl)
        {
            if (string.IsNullOrWhiteSpace(baseUrl))
            {
                return null;
            }

            return Uri.TryCreate(baseUrl, UriKind.Absolute, out Uri? uri) && !string.IsNullOrEmpty(uri.Host) ? uri.Host : null;
        }

        #endregion
    }
}
