namespace Mux.Publisher.Channels.Drivers
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Mux.Publisher.Manifest;

    /// <summary>
    /// Builds a Windows <c>.msi</c> with WiX v4/v5, for enterprise/MSI deployment scenarios where an
    /// Inno <c>.exe</c> is not sufficient. Uses the WiX v4 <c>Files</c> element to harvest the whole
    /// self-contained publish directory. Signed with the same <c>signtool</c> step as the Inno channel.
    /// </summary>
    public sealed class WixDriver : DriverBase
    {
        /// <inheritdoc />
        public override string Name => "wix";

        /// <inheritdoc />
        public override TargetOs RequiredOs => TargetOs.Windows;

        /// <inheritdoc />
        public override ChannelPlan Plan(PublisherContext context, ChannelConfig config)
        {
            if (context == null) throw new ArgumentNullException(nameof(context));
            if (config == null) throw new ArgumentNullException(nameof(config));

            ChannelPlan plan = new ChannelPlan(Name);
            string project = Project(context);
            string display = Display(context);

            foreach (string rid in ChannelHelpers.ResolveRuntimes(context.Manifest, config, RequiredOs))
            {
                PublishedArtifact? published = context.PublishedFor(rid);
                if (published == null)
                {
                    plan.AddNote("wix: no publish for " + rid + "; skipped.");
                    continue;
                }

                string wxsName = "wix/" + project + "-" + rid + ".wxs";
                string appExe = System.IO.Path.GetFileName(published.PrimaryBinary);
                string wxs = RenderWxs(new WixInputs
                {
                    ProductName = display,
                    Manufacturer = "Joel Christner",
                    Version = context.Version,
                    AppExe = appExe,
                    PublishDir = published.PublishDir,
                    Arch = rid.EndsWith("arm64", StringComparison.OrdinalIgnoreCase) ? "arm64" : "x64"
                });
                plan.AddFile(wxsName, wxs);

                string msi = Naming.Msi(project, context.Version, rid);
                string msiOut = System.IO.Path.Combine(context.OutputRoot, "windows", msi);
                plan.AddCommand(new ShellCommand("wix", new List<string>
                {
                    "build",
                    System.IO.Path.Combine(context.StagingRoot, wxsName),
                    "-arch", rid.EndsWith("arm64", StringComparison.OrdinalIgnoreCase) ? "arm64" : "x64",
                    "-o", msiOut
                })
                {
                    Description = "Build the MSI for " + rid
                });

                InnoSetupDriver.AddSigning(plan, context, config, msiOut);
            }

            return plan;
        }

        /// <summary>Inputs for rendering a WiX v4 package.</summary>
        public sealed class WixInputs
        {
            /// <summary>Product display name.</summary>
            public string ProductName { get; set; } = string.Empty;

            /// <summary>Manufacturer name.</summary>
            public string Manufacturer { get; set; } = string.Empty;

            /// <summary>Release version.</summary>
            public string Version { get; set; } = string.Empty;

            /// <summary>Main executable file name.</summary>
            public string AppExe { get; set; } = string.Empty;

            /// <summary>Publish directory to harvest.</summary>
            public string PublishDir { get; set; } = string.Empty;

            /// <summary>Package architecture (x64/arm64).</summary>
            public string Arch { get; set; } = "x64";
        }

        /// <summary>
        /// Renders a WiX v4/v5 <c>.wxs</c> that installs the whole publish directory under Program Files.
        /// </summary>
        /// <param name="inputs">The render inputs.</param>
        /// <returns>The rendered <c>.wxs</c> content.</returns>
        public static string RenderWxs(WixInputs inputs)
        {
            if (inputs == null) throw new ArgumentNullException(nameof(inputs));

            string upgradeCode = StableGuid.FromString("wix:" + inputs.ProductName);
            StringBuilder builder = new StringBuilder();
            builder.AppendLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
            builder.AppendLine("<!-- Generated by Mux.Publisher — do not edit by hand. -->");
            builder.AppendLine("<Wix xmlns=\"http://wixtoolset.org/schemas/v4/wxs\">");
            builder.AppendLine("  <Package Name=\"" + Xml(inputs.ProductName) + "\" Manufacturer=\"" + Xml(inputs.Manufacturer) + "\"");
            builder.AppendLine("           Version=\"" + Xml(inputs.Version) + "\" UpgradeCode=\"" + upgradeCode + "\" Scope=\"perMachine\">");
            builder.AppendLine("    <MajorUpgrade DowngradeErrorMessage=\"A newer version is already installed.\" />");
            builder.AppendLine("    <MediaTemplate EmbedCab=\"yes\" />");
            builder.AppendLine("    <StandardDirectory Id=\"ProgramFiles64Folder\">");
            builder.AppendLine("      <Directory Id=\"INSTALLFOLDER\" Name=\"" + Xml(inputs.ProductName) + "\" />");
            builder.AppendLine("    </StandardDirectory>");
            builder.AppendLine("    <Feature Id=\"Main\">");
            builder.AppendLine("      <Files Directory=\"INSTALLFOLDER\" Include=\"" + Xml(inputs.PublishDir) + "\\**\" />");
            builder.AppendLine("    </Feature>");
            builder.AppendLine("  </Package>");
            builder.AppendLine("</Wix>");
            return builder.ToString();
        }

        private static string Xml(string value)
        {
            return (value ?? string.Empty)
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }
    }
}
