namespace Mux.Cli.Commands
{
    using System;

    /// <summary>
    /// Normalizes session titles generated by a model or supplied by the user.
    /// </summary>
    public static class SessionTitleHelper
    {
        /// <summary>
        /// Default title used before a session has enough context to infer a better one.
        /// </summary>
        public const string DefaultTitle = "New conversation";

        #region Public-Methods

        /// <summary>
        /// Normalizes a raw title candidate into a short, single-line session title.
        /// </summary>
        /// <param name="title">The raw title candidate.</param>
        /// <param name="fallbackTitle">Fallback title used when normalization yields no content.</param>
        /// <param name="maxLength">Maximum normalized title length.</param>
        /// <returns>A normalized title.</returns>
        public static string Normalize(string? title, string? fallbackTitle = null, int maxLength = 80)
        {
            string fallback = string.IsNullOrWhiteSpace(fallbackTitle)
                ? DefaultTitle
                : fallbackTitle.Trim();

            if (string.IsNullOrWhiteSpace(title))
            {
                return fallback;
            }

            string normalized = title.Trim()
                .Replace("\r\n", "\n", StringComparison.Ordinal)
                .Replace('\r', '\n');

            int newlineIndex = normalized.IndexOf('\n');
            if (newlineIndex >= 0)
            {
                normalized = normalized.Substring(0, newlineIndex);
            }

            if (normalized.StartsWith("title:", StringComparison.OrdinalIgnoreCase))
            {
                normalized = normalized.Substring(6).Trim();
            }

            normalized = normalized.Trim(' ', '"', '\'', '`');

            while (normalized.EndsWith(".", StringComparison.Ordinal)
                || normalized.EndsWith(":", StringComparison.Ordinal)
                || normalized.EndsWith(";", StringComparison.Ordinal))
            {
                normalized = normalized.Substring(0, normalized.Length - 1).TrimEnd();
            }

            if (normalized.Length > Math.Max(1, maxLength))
            {
                normalized = normalized.Substring(0, maxLength).TrimEnd();
            }

            return string.IsNullOrWhiteSpace(normalized) ? fallback : normalized;
        }

        #endregion
    }
}
