// Generate the desktop-specific string catalog (DesktopStrings.cs) from the authored
// translation table in desktop-i18n.js. Run: node tools/i18n/gen.js
//
// desktop-i18n.js exports { "<key>": { en, es, pt, fr, it, de, zh, ar, ru, ms, hi }, ... }.
// English (en) is required per key; any locale omitted for a key falls back to English at
// runtime (LocalizationService). Keys that intentionally stay English (long help text) supply
// only `en`. Keys named after dashboard keys (e.g. "nav.endpoints") OVERRIDE the dashboard pack
// for the desktop (LocalizationService merges DesktopStrings over DashboardStrings).
const fs = require('fs');
const path = require('path');

const LANGS = ['en', 'es', 'pt', 'fr', 'it', 'de', 'zh', 'ar', 'ru', 'ms', 'hi'];
const catalog = require('./desktop-i18n.js');
const outPath = path.join(__dirname, '..', '..', 'src', 'Mux.Desktop.Core', 'I18n', 'DesktopStrings.cs');

const keys = Object.keys(catalog);
// Validate: every key must have English.
let bad = 0;
for (const k of keys) {
  if (!catalog[k] || typeof catalog[k].en !== 'string' || catalog[k].en.length === 0) {
    console.error('MISSING en for key:', k);
    bad++;
  }
}
if (bad) { throw new Error(bad + ' key(s) missing English'); }

// Build per-locale maps: a key appears in a locale only when that locale has a translation
// (English always; others only when present) so missing ones fall back to English at runtime.
const byLocale = {};
for (const lang of LANGS) { byLocale[lang] = {}; }
for (const k of keys) {
  for (const lang of LANGS) {
    const v = catalog[k][lang];
    if (typeof v === 'string' && v.length > 0) { byLocale[lang][k] = v; }
  }
}

function csEsc(s) {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\r/g, '').replace(/\n/g, '\\n');
}

let out = '';
out += 'namespace Mux.Desktop.I18n\n{\n';
out += '    using System;\n';
out += '    using System.Collections.Generic;\n\n';
out += '    /// <summary>\n';
out += '    /// Desktop-specific string catalogs. GENERATED by <c>tools/i18n/gen.js</c> from\n';
out += '    /// <c>tools/i18n/desktop-i18n.js</c> — do not edit by hand; edit the authored table and regenerate.\n';
out += '    /// Covers every desktop window/form/dialog label; keys named after dashboard keys override the\n';
out += '    /// shared pack for the desktop. Merged over <see cref="DashboardStrings"/> by\n';
out += '    /// <see cref="LocalizationService"/>; any locale missing a key falls back to English.\n';
out += '    /// </summary>\n';
out += '    internal static class DesktopStrings\n    {\n';
out += '        /// <summary>\n';
out += '        /// Build the per-locale (key → value) catalogs for the desktop-specific strings.\n';
out += '        /// </summary>\n';
out += '        /// <returns>A dictionary of locale code to its (key → value) map.</returns>\n';
out += '        internal static Dictionary<string, Dictionary<string, string>> Build()\n        {\n';
out += '            Dictionary<string, Dictionary<string, string>> all =\n';
out += '                new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase);\n\n';
for (const lang of LANGS) {
  out += '            all["' + lang + '"] = new Dictionary<string, string>(StringComparer.Ordinal)\n            {\n';
  const map = byLocale[lang];
  for (const k of Object.keys(map)) {
    out += '                { "' + csEsc(k) + '", "' + csEsc(map[k]) + '" },\n';
  }
  out += '            };\n\n';
}
out += '            return all;\n        }\n    }\n}\n';

fs.writeFileSync(outPath, out, 'utf8');

// Report coverage.
const report = {};
for (const lang of LANGS) { report[lang] = keys.length - Object.keys(byLocale[lang]).length; }
console.error('Keys:', keys.length);
console.error('Untranslated (fall back to en) per locale:', JSON.stringify(report));
console.error('Wrote', outPath, out.length, 'bytes');
